### ISSUE TITLE
[in] no files fetched

### ISSUE THREAD

**Issue by drnic** [concourse/github-release-resource#1]
See example pipeine usage https://github.com/drnic/concourse-tutorial/blob/master/40_github_release_input/pipeline.yml

It fetches the https://github.com/cloudfoundry/cli/releases latest release - but there aren't any files in the resource pool. 

Output is:

```
initializing with docker:///ubuntu#14.04
running ls -opR .
.:
total 4
drwxr-xr-x 2 vcap 4096 Apr 10 00:59 cloudfoundry-cli-release/

./cloudfoundry-cli-release:
total 0
```

Should there be files here?

**Comment by vito** [comment]
Looks like they don't actually put any artifacts in their releases; they just use them to announce things. We could maybe fetch the source but that hasn't been wanted by anyone yet (do you want that?)

**Comment by drnic** [comment]
Ahh my mistake - I pick the one project with releases but not using its upload feature.

I put the "get source" request in other ticket.
