### ISSUE TITLE
Get fails for drafted release if the associated tag is a draft tag

### ISSUE THREAD

**Issue by sclevine** [concourse/github-release-resource#12]
We get [this panic](https://gist.github.com/sclevine/7b08d0b14512e39b14cc) after creating a release that is merged into a draft, during the `get`. This happens because [this line](https://github.com/concourse/github-release-resource/blob/master/in_command.go#L44) will return an empty release when one does not exist, as the tag provided to `GetReleaseByTag` does not actually exist.

Steps to reproduce:
1. Setup a draft of a release in Github
2. Create a concourse job that publishes a release with the same name as the draft release
3. Confirm that the tag that concourse will create does not already exist in the repo
4. Start job

Strangely, this seemed to be working on our previous (0.59.0) concourse deployment.

**Comment by jtarchie** [comment]
We experienced a similar problem.

I don't have steps to reproduce, but an explanation of our current CI state and a stack trace.

# Current state

* We have a github repo where we have a [new release](https://github.com/cloudfoundry/php-buildpack/releases).
* The resource on concourse did not detect the new version. The check state only references previous releases.
* When the job runs and tries to download the resource, it panics!

# Stacktrace

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45dbc8]

goroutine 1 [running]:
github.com/concourse/github-release-resource.(*InCommand).Run(0xc20800a4e0, 0x7ffec963ef81, 0xe, 0xc20802a910, 0xc, 0xc20802a900, 0xd, 0x0, 0x0, 0xc20800ccf0, ...)
	/tmp/build/bff9c6cc-19f8-4f19-458f-9481aee1ec10/gopath/src/github.com/concourse/github-release-resource/in_command.go:55 +0xc98
main.main()
	/tmp/build/bff9c6cc-19f8-4f19-458f-9481aee1ec10/gopath/src/github.com/concourse/github-release-resource/cmd/in/in.go:27 +0x34b

goroutine 9 [runnable]:
net/http.(*persistConn).readLoop(0xc20807a160)
	/usr/src/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc20807a160)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by sclevine** [comment]
Still getting a panic in the same place (with a different line number, as the code changed):
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45da4e]

goroutine 1 [running]:
github.com/concourse/github-release-resource.(*InCommand).Run(0xc20800a580, 0x7fff1c499f81, 0xe, 0xc20800a520, 0x16, 0xc20802a930, 0x7, 0x0, 0x0, 0xc20800cd20, ...)
	/tmp/build/1478dca3-fe5c-417b-4b39-c9dad7fa50a8/gopath/src/github.com/concourse/github-release-resource/in_command.go:44 +0xc8e
main.main()
	/tmp/build/1478dca3-fe5c-417b-4b39-c9dad7fa50a8/gopath/src/github.com/concourse/github-release-resource/cmd/in/in.go:27 +0x34b
```

**Comment by vito** [comment]
@sclevine It looks like that error occurs when fetching something that's a draft release. Perhaps this was something that was detected before we fixed this? The `check` should now skip draft releases. Try disabling the version that it's trying to fetch?

**Comment by sclevine** [comment]
We encounter this panic during the implicit `get` that happens after a `put`. We're using the `put` to update a draft release that gets published at a later date. This works fine, but the failed implicit `get` causes the job to go red. Our config looks like:

```
      - put: lattice-release
        params:
          name: lattice/Version
          tag: lattice/Version
          commitish: compile-lattice-bundles/commit
          body: lattice/RELEASE_NOTES.md
          globs: [compile-lattice-bundles/*.zip]
```

There are other issues with updating a draft release (see #10, #11), but this issue is the only thing preventing our release pipeline from going green.

**Comment by vito** [comment]
Ah, good to know. Thanks.
