### ISSUE TITLE
[Idea] Body with Tag placeholder

### ISSUE THREAD

**Issue by shinji62** [concourse/github-release-resource#26]
Hi I would like to make a quick proposal about adding a tag for example #tag placeholder into the `body` option .

For example tag is (0.4.0) so I can declare the body filename like 
```
body: dir/filename_#tag resolve to dir/filename_0.4.0
body: dir/file#tagname resolve to dir/file0.4.0name
```

I am willing to made a PR if that interest someone.

**Comment by shinji62** [comment]
@mariash Any thought ?

**Comment by evanshort73** [comment]
@shinji62 I don't understand your use case. Do you have a task that generates a `body` file with a parameterized filename? If so, why can't it have a fixed name? As far as I know, the body filename has no effect on the GitHub release generated by this resource.

**Comment by shinji62** [comment]
Release are not generated by the pipeline but write by me, but I would like to separate by release tag.

Let say I want to create release notes with a file name RELEASE_NOTES_0.2.1, so when I will release this version this concourse resource will pickup the right RELEASE_NOTES, so I don't need to change my pipeline for every version.


My pipeline body parameters will be RELEASE_NOTES_#TAG

**Comment by evanshort73** [comment]
Can you instead make a task step that identifies the right file based on the tag and renames it to a fixed filename?

**Comment by shinji62** [comment]
Of course I can, but avoid doing that in all my pipeline could be nice.
Well I guess I will forget the idea to put that in the official github-release-resource.

**Comment by evanshort73** [comment]
This isn't a bad idea, but I don't know whether there's enough interest in this feature to justify making the resource more complicated. If more people request this I will consider it.
