### ISSUE TITLE
[question] should the resource create annotated tags instead of lightweight tags?

### ISSUE THREAD

**Issue by voelzmo** [concourse/github-release-resource#33]
From the git documentation at `git tag --help`: 

> Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels. For this reason, some git commands for naming objects (like git describe) will ignore lightweight tags by default.

How do you feel about switching to annotated tags then?

**Comment by jtarchie** [comment]
@voelzmo, the Github API automatically creates it as a tag. We don't have any control over that. If you create an annotated tag before, the Github release will reference that. You can use the git resource to do so.
