### ISSUE TITLE
`in` should create a file, `release_url`, which is the URL of the release

### ISSUE THREAD

**Issue by jchesterpivotal** [concourse/github-release-resource#36]
In our [php-notifications pipeline](https://github.com/cloudfoundry/buildpacks-ci/blob/master/pipelines/php-notifications.yml), we use a number of different mechanisms to consume upstream dependencies. One of these is github-release-resource, another is [new_version_resource](https://github.com/pivotal-cf-experimental/new_version_resource).

new_version_resource can supply the URL of a page that was scraped for new versions. This means that our `PHP Module Checker` job, which posts a story to tracker, can supply URLs for dependencies we're updating.

It would be nice to get a `release_url` file from github-release-resource so that we could do the same for dependencies tracked this way.

**Comment by andymoe** [comment]
This one is a nice to have for the Ops Manager team at Pivotal since we could then make some generated yml we use for automatically pulling in external dependencies a less opaque. I'm going to try and look into this.
