### ISSUE TITLE
Put occasionally fails with 422 invalid tag error

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/github-release-resource#37]
![screen shot 2016-10-27 at 3 59 55 pm](https://cloud.githubusercontent.com/assets/1178694/19783091/86119bf8-9c5e-11e6-9058-6bfabadb9267.png)

I might be doing something wrong but since this only happens very occasionally and subsequent runs of the same job with the same inputs succeeds my hunch is that this is a bug

**Comment by chendrix** [comment]
Have you seen this again in recent versions of Concourse?

**Comment by xtreme-gavin-enns** [comment]
Apologies for the slow reply, I was on vacay.

This was last seen 33 days ago. That should have been on 2.7.0

**Comment by andrewedstrom** [comment]
@xtreme-gavin-enns Do you have a set of steps we can follow to reproduce this issue or does it just happen mysteriously and intermittently?

**Comment by xtreme-gavin-enns** [comment]
Apologies for the delay - another vacay :P 

@andrewedstrom I don't have any steps to follow, afaik this happened only intermittently and hasn't been seen in months. But I've bounced around a few teams since then and the project we saw this on is on pause so I don't know if that pipeline is still seeing flakiness.

**Comment by jtarchie** [comment]
We are considering this issue dead due to inactivity. Please feel free to reopen a new issue if this is still a problem. Thanks!
