### ISSUE TITLE
Concourse pipeline to download the .pivotal from corporate git hub release

### ISSUE THREAD

**Issue by keraghu** [concourse/github-release-resource#52]
Hi Team,

From concourse pipeline, trying to download the .pivotal from corporate Git hub release, but while connecting to Git hub release, URL is appending with /repo/, due to that not able to connect to the Git hub release:
Configurations used to connect to Git hub release from concourse pipeline:
- name: pcf-custom-tiles
  type: github-release
  source:
    user: OpenPlatform
    repository: xxx-tile
    paths: [xxxxxxxxxxxxxxxx.pivotal]
    github_api_url: {{GIT_URI}}
    access_token: xxxxxxxxxxxxxxxxxxxxxx

while connecting, it reforms the git hub release URL as below:
Get https://github.xxxx.com/repos/OpenPlatform/xxx-tile/releases
It appends the /repo/ to the URL, due to that, the connection is failing,  
Can we over ride the Git Hub URL ?
Please suggest on this.

Thank you.
Raghavendra

**Comment by topherbullock** [comment]
Those endpoints formats should work for GitHub and GitHub Enterprise.
Make sure you're providing the proper API URL in `github_api_url` see: https://developer.github.com/v3/enterprise/
