### ISSUE TITLE
cannot specify older version in `get`

### ISSUE THREAD

**Issue by davidjahn** [concourse/github-release-resource#58]
Hi,

We have a use-case with the following repo:
https://github.com/PowerShell/Win32-OpenSSH/releases

Very old version of the release have timestamps, eg `5_15_2016`. The resource in a new pipeline never picks up the latest versions because it thinks these timestamps are the newest ones.

It would be nice if we could specify a tag in the resource definition. Otherwise we are forced to run `fly check-resource` every time we stand up a new pipeline or a new version comes out, which breaks the promise of statelessness in concourse pipelines.

**Comment by vito** [comment]
https://concourse.ci/get-step.html#get-step-version
