### ISSUE TITLE
get doesn't show what was added via a previous put

### ISSUE THREAD

**Issue by billimek** [concourse/github-release-resource#61]
When I `put` to an existing `github-release` in the pipeline to append a file, the next job which also does a `get` against the same resource doesn’t see the recently-added file.  Indeed when I hijack the next job and examine the resource, I see the usual `body`, `tag`, and `version` for the github-release resource but not the recently-added file.  The Github UI does show that file present for the release indicating that it was successfully added.

The [concourse documentation for `put`](http://concourse.ci/put-step.html) indicates:

> When the put succeeds, the produced version of the resource will be immediately fetched via an implicit get step. This is so that later steps in your plan can use the artifact that was produced.

This expected behavior works in a different resource type like the regular `git resource`, but does not appear to work in the github-release resource.  Is this expected behavior?

**Comment by vito** [comment]
This is working as expected of the caching semantics. When a resource version changes in-place, there's no way for Concourse to know that that same version is technically different now. I don't think it's an issue specific to this resource, but you could open a general issue to invalidate caches when a `put` is done to a version; that may be a route we can explore.
