### ISSUE TITLE
Cannot start Docker container intermittently with 'cf create-service'

### ISSUE THREAD

**Issue by bobhlo** [concourse/github-release-resource#9]
The issue is intermittent. Typically, a retry works. Any thoughts and how do we troubleshoot?

212442468@cf-sb-adm001:~/workspace/applications/rabbitmq-cloudfoundry-samples/spring$ cf cs logstash free delete-rabbitmq-logstash
Creating service instance delete-rabbitmq-logstash in org CSOps / space riak as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: #<Exceptions::BackendError: Cannot start Docker container `cf-6619f8df-b422-4769-933b-de4ce63095cc'>

**Comment by bobhlo** [comment]
Errors seem to be thrown from docker_manager.rb/create
```
    container.start(container_start_opts)

    unless container_running?(container)
      container.remove(v: true, force: true) rescue nil #nop
      raise Exceptions::BackendError, "Cannot start Docker container `#{container_name(guid)}'"
    end
```

**Comment by xoebus** [comment]
I'm not sure this relates to the Concourse GitHub release resource. Did you file this agains the correct repository?
